[local]
localhost

[mongodb]
mongodb.mydaws90.online

[redis]
redis.mydaws90.online

[mysql]
mysql.mydaws90.online

[rabbitmq]
rabbitmq.mydaws90.online

[catalogue]
catalogue.mydaws90.online

[user]
user.mydaws90.online

[cart]
cart.mydaws90.online

[shipping]
shipping.mydaws90.online

[payment]
payment.mydaws90.online

[frontend]
frontend.mydaws90.online
